# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvscan < Formula
  desc "Cloudvisor Security Scanner - secrets & IaC misconfiguration scanning"
  homepage "https://github.com/devisory-engineering/cvscan"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.0/cvscan_0.1.0_darwin_amd64.tar.gz"
      sha256 "bdeffc89c486135ab1d009e1dbb11123a522b79f6f033cd1116f31b9ccebd679"

      define_method(:install) do
        bin.install "cvscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.0/cvscan_0.1.0_darwin_arm64.tar.gz"
      sha256 "eead23cec57d0cb4fff9fcdff80504af2b7e7e4d648d3f4201f91a1e3d478208"

      define_method(:install) do
        bin.install "cvscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.0/cvscan_0.1.0_linux_amd64.tar.gz"
      sha256 "257c34ad9d144350e7b9ff1086e569db6d9133443ee648e6f396dbccabe5bf08"
      define_method(:install) do
        bin.install "cvscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.0/cvscan_0.1.0_linux_arm64.tar.gz"
      sha256 "4aa46666a8f199e561595ebce304bd1573679c91c16833efaaed63f1b2361186"
      define_method(:install) do
        bin.install "cvscan"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cvscan --version")
  end
end
