# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvscan < Formula
  desc "Cloudvisor Security Scanner - secrets & IaC misconfiguration scanning"
  homepage "https://github.com/devisory-engineering/cvscan"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.1/cvscan_0.1.1_darwin_amd64.tar.gz"
      sha256 "afcc57676309cf850414f97583411fc9b122e840845c68604c492840b0dcace2"

      define_method(:install) do
        bin.install "cvscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.1/cvscan_0.1.1_darwin_arm64.tar.gz"
      sha256 "e228cfb851fef1a3b238edab7b9590de8bf78dbf9e923d993b956a24d7bc9c69"

      define_method(:install) do
        bin.install "cvscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.1/cvscan_0.1.1_linux_amd64.tar.gz"
      sha256 "755427cb08a4f9c54f8be98f059c8d0466982ab9db8135b5228b8ccd2a0e5e8d"
      define_method(:install) do
        bin.install "cvscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devisory-engineering/cvscan/releases/download/v0.1.1/cvscan_0.1.1_linux_arm64.tar.gz"
      sha256 "7ddd6162a889814d2d63c2461f0fdf262e54672369e8deb3cbb4d48e85a009b8"
      define_method(:install) do
        bin.install "cvscan"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cvscan --version")
  end
end
